python("import maya.cmds as mayaCmds");
python("mayaCmds.moduleInfo(mn='MS_Toolkit',p=True)");


//Coded by Tiancg
global proc tjh_cut_tool_Main(){	python("import maya.cmds as mayaCmds");

string $srcPath = python("mayaCmds.moduleInfo(mn='MS_Toolkit',p=True)")+"/tools/TianCG/MST_DATA/plug-ins/tjh_cut_tool_Main/";	int $size = size($srcPath) ;		string $mayaVer=`about -v`;	string $ver[];	int $number=`tokenize $mayaVer "." $ver`;	string $plug_ins="linkDll_"+$ver[0]+".mll";	if(!` pluginInfo -query -l $plug_ins `)loadPlugin -qt ($srcPath+"/lib/"+$plug_ins);	string $dstScriptPath = python("mayaCmds.moduleInfo(mn='MS_Toolkit',p=True)")+"/tools/TianCG/MST_DATA/scripts/"; sysFile -copy ($dstScriptPath+"tjh_cut_tool.dll") ($srcPath+"/lib/"+"tjh_cut_tool.dll"); linkDll ($dstScriptPath+"tjh_cut_tool.dll");tjh_cut_tool;}tjh_cut_tool_Main;